version: '3'
services:
  api1:
    image: gabridants/rinha-backend
    volumes:
      - ./src:/usr/src/app
    ports:
      - 81
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  api2:
    image: gabridants/rinha-backend
    volumes:
      - ./src:/usr/src/app
    ports:
      - 81
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DATABASE: 'rinha'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_ROOT_PASSWORD: 'password'
      
      POSTGRES_TCP_PORT: '5434'
    ports:
      - '5434:5432'
    expose:
      - '5434'
    volumes:
      - my-db:/var/lib/POSTGRES
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
# Names our volume
volumes:
  my-db:
  

    